version: '3'
services:
  jupyter:
    build: .
    shm_size: "16g"
    container_name: jupyterlab_pytorch
    ports:
      - "8888:8888"
      - "9999:9999"  # Port for Copilot
    volumes:
      - ./data:/home/jovyan/work
      - jupyter-data:/home/jovyan
      - conda-envs:/opt/conda/envs
    environment:
      - JUPYTER_TOKEN=my-token
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

volumes:
  jupyter-data:
    name: jupyter-data
  conda-envs:
    name: conda-envs