services:
    jupyter:
      build: .
      shm_size: "16g"
      container_name: jupyterlab_pytorch
      ports:
        - "8888:8888"
        - "9999:9999"
      volumes:
        - ./jupyter-data:/home/jovyan  # Bind mount untuk akses dari host
        - conda-envs:/opt/conda/envs
      environment:
        - JUPYTER_TOKEN=my-token
        - NVIDIA_VISIBLE_DEVICES=all
        - CHOWN_HOME=yes
        - CHOWN_HOME_OPTS=-R  # Hapus tanda kutip untuk menghindari error
      runtime: nvidia
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      restart: always
      user: root 
  
  volumes:
    conda-envs:
      name: conda-envs
